In [22]:
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [23]:
#load the dataset
data = load_diabetes()
data
df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"]=data.target
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [24]:


X = df.drop("target",axis=1)
y_with_N = df.target

In [25]:
X

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [26]:
y_with_N

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [27]:
y_binary = (y_with_N > 120).astype(int)
y_binary
y_binary.value_counts()

target
1    258
0    184
Name: count, dtype: int64

In [28]:
#split into training and testing data
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y_binary,test_size=0.3,random_state=42)

In [29]:
#model training
model = GaussianNB()
model.fit(Xtrain,ytrain)

GaussianNB()

In [30]:
ypred = model.predict(Xtest)
ypred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1])

In [31]:
print("Training score: ",model.score(Xtrain,ytrain))
print("Testing score: ",model.score(Xtest,ytest))

Training score:  0.7411003236245954
Testing score:  0.7218045112781954

In [32]:
con_matrix = confusion_matrix(ytest,ypred)
con_matrix

array([[43, 16],
       [21, 53]], dtype=int64)

In [33]:

print("Accuracy: ",accuracy_score(ytest,ypred))
print("Precision: ",precision_score(ytest,ypred))
print("Recall: ",recall_score(ytest,ypred))
print("F1: ",f1_score(ytest,ypred))

Accuracy:  0.7218045112781954
Precision:  0.7681159420289855
Recall:  0.7162162162162162
F1:  0.7412587412587412

In [34]:
final_com = ytest.to_frame(name='actual')   # convert Series → DataFrame
final_com['predicted'] = ypred

final_com

     actual  predicted
287       1          1
211       0          1
72        1          1
321       1          1
73        0          1
..      ...        ...
238       1          1
26        1          0
7         0          1
401       0          0
108       1          1

[133 rows x 2 columns]

In [35]:
mismatch = final_com[final_com['actual'] != final_com['predicted']]
mismatch

     actual  predicted
211       0          1
73        0          1
78        1          0
329       1          0
55        1          0
30        1          0
140       0          1
209       0          1
39        0          1
157       0          1
199       0          1
77        1          0
395       1          0
411       1          0
131       1          0
11        0          1
19        1          0
56        0          1
244       1          0
218       1          0
388       0          1
374       1          0
185       0          1
423       0          1
46        1          0
255       1          0
24        1          0
245       1          0
153       0          1
380       0          1
278       0          1
124       1          0
63        1          0
439       1          0
298       1          0
26        1          0
7         0          1